# Site settings
title: Western Isles Yacht Club
email: secretary.wiyc at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A sailing club based on the Isle of Mull.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.wiyc.org.uk" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  wiyc

# Build settings
markdown: kramdown
